"""
EIOS Repository Port Interfaces

Protocol definitions for all domain repositories.
Infrastructure implementations must satisfy these interfaces.
The application layer depends only on these protocols, never on implementations.
"""

from typing import Protocol, runtime_checkable

from domain import (
    Assessment,
    Asset,
    Control,
    Decision,
    Evidence,
    Finding,
    Organization,
    Policy,
    Process,
    Project,
    Recommendation,
    Requirement,
    Risk,
    Sector,
    Standard,
    Task,
    User,
)


@runtime_checkable
class AssessmentRepository(Protocol):
    async def get_by_id(self, id: str) -> Assessment | None: ...
    async def list_by_sector(self, sector_id: str) -> list[Assessment]: ...
    async def save(self, assessment: Assessment) -> Assessment: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class EvidenceRepository(Protocol):
    async def get_by_id(self, id: str) -> Evidence | None: ...
    async def list_by_assessment(self, assessment_id: str) -> list[Evidence]: ...
    async def save(self, evidence: Evidence) -> Evidence: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class FindingRepository(Protocol):
    async def get_by_id(self, id: str) -> Finding | None: ...
    async def list_by_assessment(self, assessment_id: str) -> list[Finding]: ...
    async def save(self, finding: Finding) -> Finding: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class RiskRepository(Protocol):
    async def get_by_id(self, id: str) -> Risk | None: ...
    async def list_by_assessment(self, assessment_id: str) -> list[Risk]: ...
    async def list_by_sector(self, sector_id: str) -> list[Risk]: ...
    async def save(self, risk: Risk) -> Risk: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class RecommendationRepository(Protocol):
    async def get_by_id(self, id: str) -> Recommendation | None: ...
    async def save(self, recommendation: Recommendation) -> Recommendation: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class DecisionRepository(Protocol):
    async def get_by_id(self, id: str) -> Decision | None: ...
    async def save(self, decision: Decision) -> Decision: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class ControlRepository(Protocol):
    async def get_by_id(self, id: str) -> Control | None: ...
    async def save(self, control: Control) -> Control: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class RequirementRepository(Protocol):
    async def get_by_id(self, id: str) -> Requirement | None: ...
    async def list_by_source(self, source: str) -> list[Requirement]: ...
    async def save(self, requirement: Requirement) -> Requirement: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class PolicyRepository(Protocol):
    async def get_by_id(self, id: str) -> Policy | None: ...
    async def save(self, policy: Policy) -> Policy: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class StandardRepository(Protocol):
    async def get_by_id(self, id: str) -> Standard | None: ...
    async def save(self, standard: Standard) -> Standard: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class AssetRepository(Protocol):
    async def get_by_id(self, id: str) -> Asset | None: ...
    async def list_by_organization(self, organization_id: str) -> list[Asset]: ...
    async def save(self, asset: Asset) -> Asset: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class ProcessRepository(Protocol):
    async def get_by_id(self, id: str) -> Process | None: ...
    async def save(self, process: Process) -> Process: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class ProjectRepository(Protocol):
    async def get_by_id(self, id: str) -> Project | None: ...
    async def list_by_organization(self, organization_id: str) -> list[Project]: ...
    async def save(self, project: Project) -> Project: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class TaskRepository(Protocol):
    async def get_by_id(self, id: str) -> Task | None: ...
    async def list_by_project(self, project_id: str) -> list[Task]: ...
    async def save(self, task: Task) -> Task: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class UserRepository(Protocol):
    async def get_by_id(self, id: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def save(self, user: User) -> User: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class OrganizationRepository(Protocol):
    async def get_by_id(self, id: str) -> Organization | None: ...
    async def save(self, organization: Organization) -> Organization: ...
    async def delete(self, id: str) -> None: ...


@runtime_checkable
class SectorRepository(Protocol):
    async def get_by_id(self, id: str) -> Sector | None: ...
    async def get_by_nace_code(self, nace_code: str) -> Sector | None: ...
    async def list_children(self, parent_id: str) -> list[Sector]: ...
    async def save(self, sector: Sector) -> Sector: ...
    async def delete(self, id: str) -> None: ...
