"""M36 Autonomous ESG Monitoring Agents — ORM Models.

Tables:
  monitoring_agents         — agent type registry (6 built-in types)
  monitoring_agent_runs     — immutable run history per agent per org
  agent_findings            — findings generated by agents (recommendations, not facts)
  agent_alerts              — escalated alerts (INFO/WARNING/HIGH/CRITICAL)
  escalation_rules          — per-org configurable escalation rules
  recommendation_drafts     — human-approval-pending recommendation drafts
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from .base import BaseModel


class MonitoringAgentModel(BaseModel):
    """Registry of autonomous monitoring agents.

    One record per agent_type.  Seeded at startup.
    Global (not per-org) — findings/alerts carry organization_id.
    """

    __tablename__ = "monitoring_agents"
    __table_args__ = (
        UniqueConstraint("agent_type", name="uq_monitoring_agent_type"),
        Index("ix_monitoring_agents_status", "status"),
    )

    agent_type: Mapped[str] = mapped_column(String(50), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # ACTIVE | PAUSED | FAILED
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="ACTIVE")
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    run_interval_hours: Mapped[int] = mapped_column(Integer, nullable=False, default=24)
    last_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    next_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    run_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    success_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    failure_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)


class MonitoringAgentRunModel(BaseModel):
    """Immutable audit log of each agent execution.

    Scoped to a single organization per run so findings are tenant-isolated.
    """

    __tablename__ = "monitoring_agent_runs"
    __table_args__ = (
        Index("ix_monitoring_runs_agent", "agent_id"),
        Index("ix_monitoring_runs_org", "organization_id"),
        Index("ix_monitoring_runs_started", "started_at"),
    )

    agent_id: Mapped[str] = mapped_column(String(36), nullable=False)
    organization_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # RUNNING | COMPLETED | FAILED
    run_status: Mapped[str] = mapped_column(String(20), nullable=False, default="RUNNING")
    findings_generated: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    alerts_generated: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    actions_recommended: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    execution_time_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)


class AgentFindingModel(BaseModel):
    """A finding generated by a monitoring agent.

    These are recommendations/signals, not authoritative facts.
    Humans decide what to do with them.

    Explainability fields:
      rule_triggered      — which threshold/rule produced this finding
      source_data_json    — snapshot of raw data used (for audit trail)
    """

    __tablename__ = "agent_findings"
    __table_args__ = (
        Index("ix_agent_findings_org", "organization_id"),
        Index("ix_agent_findings_supplier", "supplier_id"),
        Index("ix_agent_findings_agent", "agent_id"),
        Index("ix_agent_findings_status", "finding_status"),
        Index("ix_agent_findings_severity", "severity"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    supplier_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    agent_id: Mapped[str] = mapped_column(String(36), nullable=False)
    agent_run_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    category: Mapped[str] = mapped_column(String(100), nullable=False)
    # LOW | MEDIUM | HIGH | CRITICAL
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="MEDIUM")
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    evidence: Mapped[str] = mapped_column(Text, nullable=False, default="")
    confidence_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.8)
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    # OPEN | ACKNOWLEDGED | DISMISSED | CONVERTED
    finding_status: Mapped[str] = mapped_column(String(20), nullable=False, default="OPEN")
    acknowledged_by: Mapped[str | None] = mapped_column(String(36), nullable=True)
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # Explainability
    rule_triggered: Mapped[str] = mapped_column(String(200), nullable=False, default="")
    source_data_json: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)


class AgentAlertModel(BaseModel):
    """An escalated alert surfaced to users.

    Alerts are created from findings when escalation rules match.
    """

    __tablename__ = "agent_alerts"
    __table_args__ = (
        Index("ix_agent_alerts_org", "organization_id"),
        Index("ix_agent_alerts_supplier", "supplier_id"),
        Index("ix_agent_alerts_severity", "severity"),
        Index("ix_agent_alerts_acknowledged", "acknowledged_at"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    supplier_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    agent_id: Mapped[str] = mapped_column(String(36), nullable=False)
    agent_finding_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    # INFO | WARNING | HIGH | CRITICAL
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="WARNING")
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False, default="")
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    acknowledged_by: Mapped[str | None] = mapped_column(String(36), nullable=True)


class EscalationRuleModel(BaseModel):
    """Per-org configurable escalation rules.

    condition_json examples:
      {"metric": "risk_score_delta", "operator": "lt", "threshold": -20}
      {"metric": "sanctions_exposure", "value": true}
      {"metric": "remediation_overdue_days", "operator": "gt", "threshold": 90}
    """

    __tablename__ = "escalation_rules"
    __table_args__ = (
        Index("ix_escalation_rules_org", "organization_id"),
        Index("ix_escalation_rules_agent_type", "agent_type"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # RISK_MONITOR | REGULATION_MONITOR | SUPPLIER_MONITOR | COMPLIANCE_MONITOR |
    # REMEDIATION_MONITOR | INTELLIGENCE_MONITOR | * (all agents)
    agent_type: Mapped[str] = mapped_column(String(50), nullable=False, default="*")
    condition_json: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    # INFO | WARNING | HIGH | CRITICAL
    escalation_severity: Mapped[str] = mapped_column(String(20), nullable=False, default="WARNING")
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    created_by: Mapped[str] = mapped_column(String(36), nullable=False)


class RecommendationDraftModel(BaseModel):
    """A draft recommendation generated by an agent.

    Humans must approve before a real Recommendation record is created.
    Agents may NEVER approve their own drafts.
    """

    __tablename__ = "recommendation_drafts"
    __table_args__ = (
        Index("ix_recommendation_drafts_org", "organization_id"),
        Index("ix_recommendation_drafts_supplier", "supplier_id"),
        Index("ix_recommendation_drafts_status", "draft_status"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    supplier_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    agent_id: Mapped[str] = mapped_column(String(36), nullable=False)
    agent_finding_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    recommendation_text: Mapped[str] = mapped_column(Text, nullable=False)
    rationale: Mapped[str] = mapped_column(Text, nullable=False, default="")
    confidence_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.8)
    # PENDING | APPROVED | REJECTED
    draft_status: Mapped[str] = mapped_column(String(20), nullable=False, default="PENDING")
    approved_by: Mapped[str | None] = mapped_column(String(36), nullable=True)
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    rejection_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
