"""M38 Supplier Network Intelligence — ORM Models.

Tables:
  supplier_relationships      — directed edges between suppliers
  suggested_relationships     — pending human-approval relationship proposals
  network_exposure_signals    — indirect risk exposure propagation records
  supplier_criticality        — computed criticality classification per supplier
  dependency_analyses         — org and per-supplier dependency metrics
  resilience_assessments      — resilience scoring per org / supplier
  incident_clusters           — grouped findings/signals sharing a root cause
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, Float, Index, Integer, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import text

from .base import BaseModel


class SupplierRelationshipModel(BaseModel):
    """Directed relationship edge between two suppliers within an org.

    Explainability:
      confidence   — 0.0–1.0 from discovery engine or manual override
      source       — MANUAL | DISCOVERY | IMPORT
      rationale    — human-readable reason stored immutably at creation time
    """

    __tablename__ = "supplier_relationships"
    __table_args__ = (
        Index("ix_rel_org", "organization_id"),
        Index("ix_rel_supplier", "supplier_id"),
        Index("ix_rel_related", "related_supplier_id"),
        Index("ix_rel_type", "relationship_type"),
        Index("ix_rel_status", "relationship_status"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    supplier_id: Mapped[str] = mapped_column(String(36), nullable=False)
    related_supplier_id: Mapped[str] = mapped_column(String(36), nullable=False)
    # PARENT_COMPANY SUBSIDIARY SISTER_COMPANY SHARED_COUNTRY SHARED_SECTOR
    # SHARED_SUPPLY_CHAIN SHARED_INCIDENT SHARED_LOGISTICS
    # SHARED_REGULATORY_EXPOSURE CUSTOM
    relationship_type: Mapped[str] = mapped_column(String(50), nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    source: Mapped[str] = mapped_column(String(30), nullable=False, default="MANUAL")
    rationale: Mapped[str] = mapped_column(Text, nullable=False, default="")
    relationship_status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="ACTIVE"
    )
    removed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    removed_by: Mapped[str | None] = mapped_column(String(36), nullable=True)
    calculation_inputs: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)


class SuggestedRelationshipModel(BaseModel):
    """Proposed relationship awaiting human approval.

    Generated by RelationshipDiscoveryEngine. Must be APPROVED before a
    SupplierRelationshipModel row is created. Rejected proposals are retained
    for the audit trail.
    """

    __tablename__ = "suggested_relationships"
    __table_args__ = (
        Index("ix_sugg_org", "organization_id"),
        Index("ix_sugg_supplier", "supplier_id"),
        Index("ix_sugg_status", "suggestion_status"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    supplier_id: Mapped[str] = mapped_column(String(36), nullable=False)
    related_supplier_id: Mapped[str] = mapped_column(String(36), nullable=False)
    relationship_type: Mapped[str] = mapped_column(String(50), nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    rationale: Mapped[str] = mapped_column(Text, nullable=False, default="")
    suggestion_source: Mapped[str] = mapped_column(String(50), nullable=False)
    # PENDING | APPROVED | REJECTED
    suggestion_status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="PENDING"
    )
    reviewed_by: Mapped[str | None] = mapped_column(String(36), nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    review_note: Mapped[str | None] = mapped_column(Text, nullable=True)
    calculation_inputs: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)


class NetworkExposureSignalModel(BaseModel):
    """Indirect risk exposure record.

    Captures propagated risk from an origin supplier to an impacted supplier
    through a relationship path. Severity and confidence attenuate by distance.
    """

    __tablename__ = "network_exposure_signals"
    __table_args__ = (
        Index("ix_nexp_org", "organization_id"),
        Index("ix_nexp_origin", "origin_supplier_id"),
        Index("ix_nexp_impacted", "impacted_supplier_id"),
        Index("ix_nexp_status", "exposure_status"),
        Index("ix_nexp_type", "exposure_type"),
        # P0 M38.1: prevent duplicate ACTIVE signals for same (org, origin, impacted, type)
        Index(
            "uq_nexp_active_signal",
            "organization_id",
            "origin_supplier_id",
            "impacted_supplier_id",
            "exposure_type",
            unique=True,
            postgresql_where=text("exposure_status = 'ACTIVE'"),
        ),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    origin_supplier_id: Mapped[str] = mapped_column(String(36), nullable=False)
    impacted_supplier_id: Mapped[str] = mapped_column(String(36), nullable=False)
    # SANCTIONS | HIGH_RISK_COUNTRY | REGULATORY | HUMAN_RIGHTS | CASCADE | CUSTOM
    exposure_type: Mapped[str] = mapped_column(String(50), nullable=False)
    propagation_path: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    path_length: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="MEDIUM")
    rationale: Mapped[str] = mapped_column(Text, nullable=False, default="")
    source_signal_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    source_finding_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    # ACTIVE | RESOLVED | DISMISSED
    exposure_status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="ACTIVE"
    )
    detected_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    calculation_inputs: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)


class SupplierCriticalityModel(BaseModel):
    """Computed criticality classification for a supplier.

    Recalculated on demand; latest record is the current classification.
    calculation_inputs stores the full snapshot for explainability.
    """

    __tablename__ = "supplier_criticality"
    __table_args__ = (
        Index("ix_crit_org", "organization_id"),
        Index("ix_crit_supplier", "supplier_id"),
        Index("ix_crit_level", "criticality"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    supplier_id: Mapped[str] = mapped_column(String(36), nullable=False)
    # LOW | MEDIUM | HIGH | CRITICAL
    criticality: Mapped[str] = mapped_column(String(20), nullable=False)
    criticality_score: Mapped[float] = mapped_column(Float, nullable=False)
    degree_centrality: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    inbound_degree: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    outbound_degree: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    connected_component_size: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1
    )
    dependency_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    assessment_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    finding_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    open_remediation_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0
    )
    calculation_inputs: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    calculated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )


class DependencyAnalysisModel(BaseModel):
    """Dependency metrics for an org or a specific supplier.

    supplier_id = None → org-level aggregate.
    """

    __tablename__ = "dependency_analyses"
    __table_args__ = (
        Index("ix_dep_org", "organization_id"),
        Index("ix_dep_supplier", "supplier_id"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    supplier_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    dependency_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    concentration_score: Mapped[float] = mapped_column(
        Float, nullable=False, default=0.0
    )
    diversification_score: Mapped[float] = mapped_column(
        Float, nullable=False, default=0.0
    )
    critical_supplier_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0
    )
    single_point_of_failure_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0
    )
    calculation_inputs: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    calculated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )


class ResilienceAssessmentModel(BaseModel):
    """Resilience scoring for an org or a specific supplier.

    supplier_id = None → org-level.
    """

    __tablename__ = "resilience_assessments"
    __table_args__ = (
        Index("ix_res_org", "organization_id"),
        Index("ix_res_supplier", "supplier_id"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    supplier_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    resilience_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    diversification_score: Mapped[float] = mapped_column(
        Float, nullable=False, default=0.0
    )
    concentration_score: Mapped[float] = mapped_column(
        Float, nullable=False, default=0.0
    )
    redundancy_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    calculation_inputs: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    calculated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )


class IncidentClusterModel(BaseModel):
    """Group of findings/risks/signals that share a probable root cause.

    affected_supplier_ids, finding_ids, signal_ids, risk_ids, compliance_gap_ids
    are stored as JSONB arrays to avoid a heavy join table while keeping the
    model simple for an application-layer service.
    """

    __tablename__ = "incident_clusters"
    __table_args__ = (
        Index("ix_cluster_org", "organization_id"),
        Index("ix_cluster_status", "cluster_status"),
        Index("ix_cluster_severity", "severity"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    cluster_name: Mapped[str] = mapped_column(String(500), nullable=False)
    root_cause: Mapped[str] = mapped_column(Text, nullable=False, default="")
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="MEDIUM")
    # ACTIVE | RESOLVED
    cluster_status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="ACTIVE"
    )
    affected_supplier_ids: Mapped[list] = mapped_column(
        JSONB, nullable=False, default=list
    )
    finding_ids: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    signal_ids: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    risk_ids: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    compliance_gap_ids: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    resolved_by: Mapped[str | None] = mapped_column(String(36), nullable=True)
    calculation_inputs: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)


class NetworkWatchlistEntryModel(BaseModel):
    """Network expansion of a supplier watchlist entry.

    When a supplier is added to SupplierWatchlistModel, all suppliers in its
    BFS neighborhood (depth ≤ 2) are recorded here so that HIGH/CRITICAL
    signals on related suppliers surface as watchlist alerts.
    """

    __tablename__ = "network_watchlist_entries"
    __table_args__ = (
        Index("ix_nwl_org", "organization_id"),
        Index("ix_nwl_watched", "watched_supplier_id"),
        Index("ix_nwl_related", "related_supplier_id"),
        # Each related supplier appears only once per watched supplier
        UniqueConstraint(
            "organization_id",
            "watched_supplier_id",
            "related_supplier_id",
            name="uq_nwl_pair",
        ),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    watched_supplier_id: Mapped[str] = mapped_column(String(36), nullable=False)
    related_supplier_id: Mapped[str] = mapped_column(String(36), nullable=False)
    distance: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
