"""M37 Continuous ESG Risk Surveillance — ORM Models.

Tables:
  surveillance_signals      — immutable risk observations (signals)
  supplier_watchlists       — flagged suppliers requiring heightened attention
  risk_episodes             — grouped signals forming a risk story
  risk_trends               — historical ESG/risk score trend per supplier per period
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from .base import BaseModel


class SurveillanceSignalModel(BaseModel):
    """An immutable surveillance observation.

    Signals are generated by engines (drift, emerging risk, correlation,
    early warning, predictive escalation). They are never modified after
    creation — status transitions only (ACTIVE → ACKNOWLEDGED/EXPIRED/DISMISSED).

    explainability_json stores the full snapshot:
      rule_triggered, source_data, thresholds, confidence, timestamps.
    """

    __tablename__ = "surveillance_signals"
    __table_args__ = (
        Index("ix_signals_org", "organization_id"),
        Index("ix_signals_supplier", "supplier_id"),
        Index("ix_signals_status", "signal_status"),
        Index("ix_signals_severity", "severity"),
        Index("ix_signals_detected_at", "detected_at"),
        Index("ix_signals_type", "signal_type"),
        Index("ix_signals_episode", "episode_id"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    supplier_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    source_type: Mapped[str] = mapped_column(String(50), nullable=False)
    source_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    signal_type: Mapped[str] = mapped_column(String(50), nullable=False)
    # CRITICAL | HIGH | MEDIUM | LOW | INFO
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="MEDIUM")
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # ACTIVE | ACKNOWLEDGED | EXPIRED | DISMISSED
    signal_status: Mapped[str] = mapped_column(String(20), nullable=False, default="ACTIVE")
    acknowledged_by: Mapped[str | None] = mapped_column(String(36), nullable=True)
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    episode_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    # Explainability snapshot — immutable at creation
    explainability_json: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    # Dedup key — prevents duplicate signals of same type for same supplier
    dedupe_key: Mapped[str | None] = mapped_column(String(300), nullable=True)


class SupplierWatchlistModel(BaseModel):
    """A supplier flagged for heightened surveillance.

    Auto-added when:
      - repeated HIGH/CRITICAL alerts
      - severe ESG/risk score deterioration
      - repeated compliance gaps

    Manually added/removed by analysts.
    One active entry per (org, supplier) — resolved via unique constraint.
    """

    __tablename__ = "supplier_watchlists"
    __table_args__ = (
        UniqueConstraint("organization_id", "supplier_id", name="uq_watchlist_org_supplier"),
        Index("ix_watchlist_org", "organization_id"),
        Index("ix_watchlist_supplier", "supplier_id"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    supplier_id: Mapped[str] = mapped_column(String(36), nullable=False)
    watch_reason: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # CRITICAL | HIGH | MEDIUM | LOW
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="HIGH")
    # MANUAL | AUTO_ALERTS | AUTO_SCORE | AUTO_COMPLIANCE
    added_by_type: Mapped[str] = mapped_column(String(30), nullable=False, default="MANUAL")
    created_by: Mapped[str | None] = mapped_column(String(36), nullable=True)
    removed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    removed_by: Mapped[str | None] = mapped_column(String(36), nullable=True)
    # ACTIVE | REMOVED
    watchlist_status: Mapped[str] = mapped_column(String(20), nullable=False, default="ACTIVE")


class RiskEpisodeModel(BaseModel):
    """A group of related surveillance signals forming a risk narrative.

    Episodes collect signals about the same supplier risk theme.
    Status: OPEN → MONITORING → RESOLVED.
    Agents create and update episodes; humans resolve them.
    """

    __tablename__ = "risk_episodes"
    __table_args__ = (
        Index("ix_episodes_org", "organization_id"),
        Index("ix_episodes_supplier", "supplier_id"),
        Index("ix_episodes_status", "episode_status"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    supplier_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # CRITICAL | HIGH | MEDIUM | LOW
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="HIGH")
    # OPEN | MONITORING | RESOLVED
    episode_status: Mapped[str] = mapped_column(String(20), nullable=False, default="OPEN")
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    signal_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    resolved_by: Mapped[str | None] = mapped_column(String(36), nullable=True)


class RiskTrendModel(BaseModel):
    """Historical risk trend record for a supplier in a given period.

    One record per (supplier, period). Period format: 'YYYY-MM' (monthly).
    Trend is computed from score snapshots within the period.
    """

    __tablename__ = "risk_trends"
    __table_args__ = (
        UniqueConstraint(
            "organization_id", "supplier_id", "period", name="uq_risk_trend_org_supplier_period"
        ),
        Index("ix_risk_trends_supplier", "supplier_id"),
        Index("ix_risk_trends_org_period", "organization_id", "period"),
    )

    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    supplier_id: Mapped[str] = mapped_column(String(36), nullable=False)
    # Monthly period: 'YYYY-MM'
    period: Mapped[str] = mapped_column(String(7), nullable=False)
    esg_score_start: Mapped[float | None] = mapped_column(Float, nullable=True)
    esg_score_end: Mapped[float | None] = mapped_column(Float, nullable=True)
    risk_score_start: Mapped[float | None] = mapped_column(Float, nullable=True)
    risk_score_end: Mapped[float | None] = mapped_column(Float, nullable=True)
    score_delta: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    # IMPROVING | STABLE | DETERIORATING
    trend: Mapped[str] = mapped_column(String(20), nullable=False, default="STABLE")
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    signal_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    computed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
