"""Prometheus metrics for the AI Sustainability Copilot — M33.2.

Metrics are registered as module-level singletons. Import this module once
at startup (via the metrics router) and call the update functions wherever
the relevant events occur in the application layer.

Naming convention: copilot_<event>_total for counters, copilot_<metric> for gauges.
"""

from __future__ import annotations

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    REGISTRY,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
)

# ── Counters ──────────────────────────────────────────────────────────────────

copilot_questions_total = Counter(
    "copilot_questions_total",
    "Total number of questions submitted to the Copilot",
    ["org_id", "intent"],
)

copilot_answers_total = Counter(
    "copilot_answers_total",
    "Total number of answers generated by the Copilot",
    ["org_id", "confidence_level"],
)

copilot_empty_context_total = Counter(
    "copilot_empty_context_total",
    "Total number of questions that returned no retrieved data",
    ["org_id"],
)

copilot_contradictions_detected_total = Counter(
    "copilot_contradictions_detected_total",
    "Total number of data contradictions detected pre-LLM",
    ["org_id", "contradiction_type"],
)

copilot_feedback_positive_total = Counter(
    "copilot_feedback_positive_total",
    "Total number of 'helpful' feedback submissions",
    ["org_id"],
)

copilot_feedback_negative_total = Counter(
    "copilot_feedback_negative_total",
    "Total number of negative feedback submissions (not_helpful, incorrect, outdated)",
    ["org_id", "rating"],
)

copilot_context_truncations_total = Counter(
    "copilot_context_truncations_total",
    "Total number of answers where context was truncated due to budget limit",
    ["org_id"],
)

# ── Histograms ────────────────────────────────────────────────────────────────

copilot_response_time_ms = Histogram(
    "copilot_response_time_ms",
    "End-to-end Copilot response time in milliseconds",
    ["org_id", "intent"],
    buckets=[100, 250, 500, 1000, 2000, 5000, 10000, 30000],
)

# ── Gauges ────────────────────────────────────────────────────────────────────

copilot_average_confidence_score = Gauge(
    "copilot_average_confidence_score",
    "Rolling average confidence score (1=Low, 4=Very High)",
    ["org_id"],
)


# ── Helper functions ──────────────────────────────────────────────────────────


def record_question(org_id: str, intent: str) -> None:
    copilot_questions_total.labels(org_id=org_id, intent=intent).inc()


def record_answer(
    org_id: str,
    confidence_level: str,
    generation_ms: int,
    intent: str,
) -> None:
    copilot_answers_total.labels(org_id=org_id, confidence_level=confidence_level).inc()
    copilot_response_time_ms.labels(org_id=org_id, intent=intent).observe(generation_ms)


def record_empty_context(org_id: str) -> None:
    copilot_empty_context_total.labels(org_id=org_id).inc()


def record_contradiction(org_id: str, contradiction_type: str) -> None:
    copilot_contradictions_detected_total.labels(
        org_id=org_id, contradiction_type=contradiction_type
    ).inc()


def record_feedback(org_id: str, rating: str) -> None:
    if rating == "helpful":
        copilot_feedback_positive_total.labels(org_id=org_id).inc()
    else:
        copilot_feedback_negative_total.labels(org_id=org_id, rating=rating).inc()


def record_context_truncation(org_id: str) -> None:
    copilot_context_truncations_total.labels(org_id=org_id).inc()


def get_metrics_text() -> tuple[bytes, str]:
    """Return (metrics_bytes, content_type) for the /metrics endpoint."""
    return generate_latest(REGISTRY), CONTENT_TYPE_LATEST
