"""Supplier Digital Twin — Domain Entities.

The Supplier Digital Twin is the living intelligence state of a supplier.
It aggregates internal knowledge (assessments, findings, risks) with
external intelligence (signals, country risk, NGO reports) into a
continuously updated, explainable state.

Architecture:
  - SupplierDigitalTwin: one per supplier per org — the current state
  - IntelligenceTimelineEvent: append-only log of all events that shaped the twin
  - The twin is NEVER static. Every external event updates it.
  - Health scoring is DETERMINISTIC and AUDITABLE — no LLM-based scoring.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime

from .base_entity import BaseEntity

# ── Twin Health Dimensions ────────────────────────────────────────────────────


@dataclass(slots=True, kw_only=True)
class SupplierDigitalTwin(BaseEntity):
    """Current intelligence state of a Supplier Digital Twin.

    Health dimensions are 0–100, where 100 = perfect health (no risk).
    Scores decrease when adverse external events are processed and
    recover gradually over time (+1/30 days without new events).

    All scoring is deterministic: signal_type × severity → dimension delta.
    See health_engine.py for the full mapping table.
    """

    supplier_id: str
    organization_id: str

    # ── Health Dimensions (0–100, 100 = perfect) ─────────────────────────────
    esg_health: float = 75.0
    compliance_health: float = 75.0
    financial_health: float = 75.0
    geopolitical_health: float = 75.0
    cyber_health: float = 75.0
    human_rights_health: float = 75.0
    environmental_health: float = 75.0
    operational_health: float = 75.0

    # ── Overall ───────────────────────────────────────────────────────────────
    overall_health: float = 75.0
    health_trend: str = "STABLE"  # IMPROVING | STABLE | DETERIORATING
    ai_confidence: float = 0.7  # Model confidence in the twin state

    # ── Aggregated counters ───────────────────────────────────────────────────
    open_recommendations: int = 0
    open_actions: int = 0
    event_count: int = 0
    critical_event_count: int = 0
    last_event_at: datetime | None = None

    # ── Snapshot metadata ─────────────────────────────────────────────────────
    last_updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    twin_version: int = 1  # bumped on every state change


@dataclass(slots=True, kw_only=True)
class IntelligenceTimelineEvent(BaseEntity):
    """A single event in a supplier's intelligence timeline.

    The timeline is append-only. Every external signal, assessment,
    certificate expiry, regulation change, or corrective action creates
    an event. The AI reasoning fields (why_important, regulatory_impact,
    recommended_action) are generated by Claude but the health_delta
    and twin_dimension_affected are always deterministic.

    Traceability fields ensure every event can be fully explained:
    - source_type / source_name / source_url: where the event came from
    - evidence_ids: links to stored evidence records
    - regulation_ids: affected regulations
    - risk_ids: affected risk records
    - signal_id: the originating ExternalRiskSignal (if applicable)
    """

    supplier_id: str
    organization_id: str

    # ── Classification ────────────────────────────────────────────────────────
    event_type: str  # EXTERNAL_SIGNAL | ASSESSMENT_COMPLETED | FINDING_CREATED |
    # CERTIFICATE_EXPIRED | REGULATION_PUBLISHED | CORRECTIVE_ACTION |
    # COUNTRY_RISK_CHANGE | NGO_REPORT | FINANCIAL_DOWNGRADE
    event_category: str  # ESG | COMPLIANCE | FINANCIAL | GEOPOLITICAL | CYBER |
    # HUMAN_RIGHTS | ENVIRONMENTAL | OPERATIONAL
    severity: str  # CRITICAL | HIGH | MEDIUM | LOW | INFO

    # ── Content ───────────────────────────────────────────────────────────────
    title: str
    summary: str

    # ── AI Reasoning (explainability) ─────────────────────────────────────────
    why_important: str = ""
    regulatory_impact: str = ""
    recommended_action: str = ""

    # ── Traceability ──────────────────────────────────────────────────────────
    source_type: str = ""  # EXTERNAL_DATASET | INTERNAL | MANUAL
    source_name: str = ""  # e.g. "UN Sanctions", "ILO", "Transparency International"
    source_url: str = ""
    evidence_ids: str = "[]"  # JSON array of evidence UUIDs
    regulation_ids: str = "[]"  # JSON array of regulation UUIDs
    risk_ids: str = "[]"  # JSON array of risk UUIDs
    signal_id: str = ""  # originating ExternalRiskSignal.id

    # ── Twin Impact ───────────────────────────────────────────────────────────
    twin_dimension_affected: str = ""  # which health dimension was updated
    health_delta: float = 0.0  # how much the score changed (negative = deterioration)
    confidence: float = 0.7

    # ── Timing ───────────────────────────────────────────────────────────────
    occurred_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    processed_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    is_active: bool = True
